version: "3.4"
services:
  # This is the main database where data is persisted.
  mongo:
    image: ${PROVENDB_PROXY_MONGO_IMAGE}
    container_name: mongo
    restart: always
    networks:
      - provendb
    hostname: mongo
    volumes: 
      - ${PROVENDB_PROXY_MONGO_DATA_MOUNT}:/data/db
    ports: 
      - ${PROVENDB_PROXY_MONGO_EXPOSE_PORT}:27017
    # healthcheck:
    #   test: ["CMD-SHELL", "mongo -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD  --port $$MONGODB_PORT --eval 'typeof rs.status().members[0] === \"undefined\" ? quit(1) : quit(0)'"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 600s
    command: [ "--bind_ip_all", "--replSet", "rs0", "--wiredTigerCacheSizeGB", "1.5", "--port", "27017"]

  # This container performs all initializations. Changes to init scripts are made in the
  # /scripts/init.sh file. 
  init:
    image: ${PROVENDB_PROXY_MONGO_IMAGE}
    container_name: mongoinit
    depends_on:
      - mongo
    restart: "no"
    networks:
      - provendb
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
    entrypoint: [ "bash", "/scripts/init.sh"]      

# This network is used for communication between containers.
networks:
  provendb:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400  