# Copyright © 2019 Southbank Software. All rights reserved. 

# Southbank Software provides this Software for non-commercial purposes only.  By installing or running this Software, 
# you acknowledge and agree that you have read the terms of this Agreement and agree to be legally bound to them. 

# This Agreement describes the licensing of the Software on a non-commercial basis.

# If User desires to use the Software on a commercial basis, it must separately purchase a commercial-use license from Southbank Software.
 
# Subject to the other terms of this Agreement, Southbank Software  grants you a three-month free-of-charge, 
# non-exclusive, non-transferable, non-commercial license to use the Software for non-commercial, 
# evaluation purposes in User’s internal business operations

# By installing or running this Software, you agree: 

# * Not to use this Software in any type of  service or outsourcing environment 
#   where the functionality of the Software is provided to a third party;
# * Not to perform reverse engineering, decompiling, disassembly, or translation of the 
#   Software to discover the source code
# * Not to evaluate the Software with the  purpose of competing with Southbank Software

# Southbank Software reserves all rights not expressly granted.

# --------------------------------------------------------
version: "3.4"
services:
  mongo:
    container_name: mongo
    restart: always
    networks:
      - provendb  
    env_file:
      - env/creds-standalone/root.env
      - env/creds-standalone/provendb.env 

  treecache:
    restart: always
    container_name: provendb-tree-cache
    networks:
      - provendb  
    env_file:
      - env/creds-standalone/root.env

  concierge:
    depends_on: 
      - mongo
    restart: on-failure
    container_name: provendb-concierge
    links:
      - mongo
    networks:
      - provendb    
    env_file:
      - env/creds-standalone/provendb.env  

  mongoauth:
    restart: always
    container_name: mongoauth
    networks:
      - provendb  
    env_file:
      - env/creds-standalone/provendb.env     

  tree:
    restart: always
    depends_on: 
      - treecache
      - mongo
      - concierge
    container_name: provendb-tree
    links:
      - treecache
      - mongo 
      - concierge
    networks:
      - provendb    
    env_file:
      - env/creds-standalone/provendb.env
      - env/creds-standalone/root.env

  proxy:
    restart: on-failure
    depends_on: 
      - mongo
      - tree
      - mongoauth
      - concierge
      - anchor
    container_name: provendb-proxy
    links:
      - concierge
      - mongo 
      - tree
      - mongoauth
      - anchor
    networks:
      - provendb    
    env_file:
      - env/creds-standalone/provendb.env

  anchor:
    container_name: provendb-anchor
    restart: always
    networks:
      - provendb  
    env_file:
      - env/creds-standalone/anchor.env     

  # This is needed in standalone mode as heath checks will not automatically restart containers on failure
  autoheal:
    depends_on: 
      - mongo
      - tree
      - mongoauth
      - concierge
      - proxy
      - treecache
      - anchor
    image: willfarrell/autoheal
    hostname: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    networks:
      - provendb    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  

networks:
  provendb:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400      
        
   